# Generated by Django 4.1.7 on 2023-03-17 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_remove_project_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='candidates',
            field=models.ManyToManyField(blank=True, related_name='projects_candidate', to=settings.AUTH_USER_MODEL),
        ),
    ]
