# Generated by Django 4.1.7 on 2023-03-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
